/** Early-career friendly titles — merged with ANZSCO IT taxonomy for search. */
export const EARLY_CAREER_IT_ROLES = [
  "Software Developer",
  "Frontend Developer",
  "Backend Developer",
  "Full Stack Developer",
  "Web Developer",
  "Mobile App Developer",
  "UI/UX Designer",
  "QA Tester",
  "Automation Tester",
  "Business Analyst",
  "Data Analyst",
  "Junior Data Scientist",
  "AI/ML Intern",
  "Cybersecurity Analyst",
  "Cloud Support Associate",
  "DevOps Engineer",
  "IT Support Specialist",
  "Systems Administrator",
  "Network Support Engineer",
  "Technical Support Analyst",
  "Game Developer",
  "Embedded Systems Developer",
  "Product Analyst",
  "Scrum Coordinator",
  "Software Engineer Intern",
  "Graduate Developer",
  "Junior Programmer",
];

/**
 * Default skill suggestions when user picks a role (exact title match).
 * Includes labels that may not exist in taxonomy — still shown as chips / auto-selected.
 */
export const ROLE_TO_SUGGESTED_SKILLS = {
  "Frontend Developer": [
    "HTML",
    "CSS",
    "JavaScript",
    "React",
    "TypeScript",
    "Git",
    "Responsive Design",
  ],
  "Backend Developer": ["Node.js", "Express", "APIs", "SQL", "MongoDB", "Authentication", "Git"],
  "Full Stack Developer": [
    "JavaScript",
    "React",
    "Node.js",
    "SQL",
    "REST APIs",
    "Git",
    "HTML",
    "CSS",
  ],
  "Software Developer": ["Python", "Git", "SQL", "Debugging", "Testing", "Problem-solving"],
  "Web Developer": ["HTML", "CSS", "JavaScript", "Git", "Responsive Design", "REST APIs"],
  "Mobile App Developer": ["Swift", "Kotlin", "Git", "REST APIs", "Mobile UI", "Testing"],
  "UI/UX Designer": ["Figma", "Wireframing", "Prototyping", "User Research", "Accessibility"],
  "QA Tester": ["Test cases", "Manual testing", "Bug tracking", "Regression testing", "Attention to detail"],
  "Automation Tester": ["Selenium", "Test automation", "CI/CD", "Python", "API testing"],
  "Business Analyst": ["Requirements gathering", "Stakeholder communication", "Documentation", "Excel", "SQL"],
  "Data Analyst": ["Python", "SQL", "Excel", "Power BI", "Tableau", "Data Cleaning"],
  "Junior Data Scientist": ["Python", "SQL", "Statistics", "Pandas", "Machine learning basics"],
  "AI/ML Intern": ["Python", "Machine learning", "Data preprocessing", "Git", "Experiment tracking"],
  "Cybersecurity Analyst": ["Security monitoring", "Incident response", "Networking basics", "Risk awareness"],
  "Cloud Support Associate": ["AWS", "Troubleshooting", "Ticketing", "Documentation", "Customer communication"],
  "DevOps Engineer": ["Docker", "CI/CD", "Linux", "Git", "Kubernetes", "Shell scripting"],
  "IT Support Specialist": ["Troubleshooting", "Windows", "Ticketing", "Networking basics", "Customer service"],
  "Systems Administrator": ["Linux", "Windows Server", "Networking", "Backup", "Monitoring"],
  "Network Support Engineer": ["Networking", "TCP/IP", "Troubleshooting", "Documentation"],
  "Technical Support Analyst": ["Troubleshooting", "Documentation", "Customer communication", "Ticketing"],
  "Game Developer": ["Unity", "C#", "Game physics", "Git", "3D basics"],
  "Embedded Systems Developer": ["C", "Microcontrollers", "Debugging", "Hardware interfaces"],
  "Product Analyst": ["SQL", "Excel", "Documentation", "Stakeholder communication", "Metrics"],
  "Scrum Coordinator": ["Agile", "Scrum", "Documentation", "Stakeholder communication", "Organization"],
  "Software Engineer Intern": ["Git", "Python", "JavaScript", "Testing", "Code review"],
  "Graduate Developer": ["Git", "Python", "JavaScript", "SQL", "Testing"],
  "Junior Programmer": ["Git", "Python", "JavaScript", "Debugging", "Problem-solving"],
};
